export const REGISTER_RRQUEST = 'REGISTER_RRQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOGIN_RRQUEST = 'LOGIN_RRQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE' 

export const GET_USER_RRQUEST = 'GET_USER_RRQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE' 

export const ADD_TO_FAVORITE_RRQUEST = 'ADD_TO_FAVORITE_RRQUEST'
export const ADD_TO_FAVORITE_SUCCESS = 'ADD_TO_FAVORITE_SUCCESS'
export const ADD_TO_FAVORITE_FAILURE = 'ADD_TO_FAVORITE_FAILURE' 

export const LOGOUT = 'LOGOUT'

export const FORGOT_PASSWORD_RRQUEST = 'FORGOT_PASSWORD_RRQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE' 

export const RESET_PASSWORD_RRQUEST = 'RESET_PASSWORD_RRQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE' 

export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'
export const CREATE_ADDRESS_FAILURE = 'CREATE_ADDRESS_FAILURE'

export const GET_USER_ADDRESS_REQUEST = 'GET_USER_ADDRESS_REQUEST'
export const GET_USER_ADDRESS_SUCCESS = 'GET_USER_ADDRESS_SUCCESS'
export const GET_USER_ADDRESS_FAILURE = 'GET_USER_ADDRESS_FAILURE'

export const GET_USER_FAVOURITE_REQUEST = 'GET_USER_FAVOURITE_REQUEST'
export const GET_USER_FAVOURITE_SUCCESS = 'GET_USER_FAVOURITE_SUCCESS'
export const GET_USER_FAVOURITE_FAILURE = 'GET_USER_FAVOURITE_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'